version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins_krumpi
    user: root
    ports:
      - "8082:8080"
    environment:
      - JENKINS_ADMIN_PASSWORD=admin
       # aici va veti pune singuri tokenul generat in SonarQube pentru a-l putea folosi in Jenkins
      - SONAR_TOKEN=squ_16e4a6a4b11f66dc8c6060d474b8fe0be702cf89
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ci-net

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube-krumpi
    ports:
      - "9000:9000"
    networks:
      - ci-net

  db:
    image: postgres:15-alpine
    container_name: krumpi_db
    environment:
      POSTGRES_DB: krumpi_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: catalina
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ci-net

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: krumpi_app
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/krumpi_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: catalina
    depends_on:
      - db
    networks:
      - ci-net

volumes:
  postgres_data:
  jenkins_data:

networks:
  ci-net:
