ALTER TABLE order_item
  ALTER COLUMN quantity TYPE DOUBLE PRECISION,
  ALTER COLUMN unit_price TYPE DOUBLE PRECISION;

ALTER TABLE product
  ALTER COLUMN quantity TYPE DOUBLE PRECISION;

ALTER TABLE stock_entry
  ALTER COLUMN quantity TYPE DOUBLE PRECISION;
