ALTER TABLE order_item
ALTER COLUMN quantity TYPE DOUBLE PRECISION
    USING quantity::DOUBLE PRECISION;

ALTER TABLE order_item
ALTER COLUMN unit_price TYPE DOUBLE PRECISION
    USING unit_price::DOUBLE PRECISION;

ALTER TABLE product
ALTER COLUMN quantity TYPE DOUBLE PRECISION
    USING quantity::DOUBLE PRECISION;

ALTER TABLE stock_entry
ALTER COLUMN quantity TYPE DOUBLE PRECISION
    USING quantity::DOUBLE PRECISION;
