spring.config.import=classpath:application.properties
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5436/krumpi_zsolt_db
spring.datasource.username=postgres
spring.datasource.password=root
