spring.config.import=classpath:application.properties
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5436/krumpi_andreea_db
spring.datasource.username=postgres
spring.datasource.password=root
