--SELECT setval(pg_get_serial_sequence('orders','id'),
--       CASE WHEN COALESCE(MAX(id), 0) = 0 THEN 1 ELSE COALESCE(MAX(id), 0) END,
--       false)
--FROM orders;
--
--INSERT INTO orders (customer_name, creation_date, status, responsible_employee_id)
--VALUES
--  ('Acme Corp',         now(), 'PENDING',     3),
--  ('Globex Industries', now(), 'PROCESSING',  1),
--  ('Soylent Co',        now(), 'DELIVERED',   2)
--ON CONFLICT DO NOTHING;
